# Generated by Django 3.2.3 on 2021-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaporGirdiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(max_length=50, verbose_name='Saha No')),
                ('saha_kod', models.CharField(max_length=50, verbose_name='Saha Kod')),
                ('ref_1', models.CharField(max_length=50, verbose_name='Referans-1')),
                ('ref_2', models.CharField(max_length=50, verbose_name='Referans-2')),
                ('ref_3', models.CharField(max_length=50, verbose_name='Referans-3')),
                ('ref_4', models.CharField(max_length=50, verbose_name='Referans-4')),
                ('ref_5', models.CharField(max_length=50, verbose_name='Referans-5')),
                ('ref_6', models.CharField(max_length=50, verbose_name='Referans-6')),
                ('ref_grup', models.CharField(max_length=5000, verbose_name='Ref Grup')),
                ('sonuc', models.CharField(max_length=50, verbose_name='Sonuç')),
                ('kontrol', models.CharField(max_length=5000, verbose_name='Kontrol')),
                ('kategori', models.CharField(max_length=50, verbose_name='Kategori')),
                ('sorgu_no', models.CharField(max_length=50, verbose_name='Sorgu No')),
                ('aciklama', models.CharField(blank=True, default='', max_length=5000, verbose_name='Açıklama')),
            ],
        ),
    ]
