# Generated by Django 3.2.3 on 2021-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamVeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(max_length=50, verbose_name='Saha No')),
                ('saha_kod', models.CharField(max_length=50, verbose_name='Saha Kod')),
                ('kts_saha_no', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('saha_tipi', models.CharField(max_length=5000, verbose_name='Saha Tipi')),
                ('ana_yer_tipi', models.CharField(max_length=5000, verbose_name='Ana Yer Tipi')),
                ('ekipman_no', models.CharField(max_length=5000, verbose_name='Ekipman No')),
                ('ekipman_seri_no', models.CharField(max_length=5000, verbose_name='Ekipman Seri No')),
                ('ekipman_parca_kodu', models.CharField(max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(max_length=5000, verbose_name='Parça Tanımı')),
                ('stok_tipi_1', models.CharField(max_length=5000, verbose_name='Stok Tipi-1')),
                ('stok_tipi_2', models.CharField(max_length=5000, verbose_name='Stok Tipi-2')),
                ('stok_tipi_3', models.CharField(max_length=5000, verbose_name='Stok Tipi-3')),
                ('stok_tipi_4', models.CharField(max_length=5000, verbose_name='Stok Tipi-4')),
                ('stok_tipi_5', models.CharField(max_length=5000, verbose_name='Stok Tipi-5')),
                ('stok_tipi_6', models.CharField(max_length=5000, verbose_name='Stok Tipi-6')),
                ('stok_tipi_7', models.CharField(max_length=5000, verbose_name='Stok Tipi-7')),
                ('stok_tipi_8', models.CharField(max_length=5000, verbose_name='Stok Tipi-8')),
                ('teslim_alma_tarihi', models.CharField(max_length=5000, verbose_name='Teslim Alma Tarihi')),
                ('sahaya_kurulum_tarihi', models.CharField(max_length=5000, verbose_name='Sahaya Kurulum Tarihi')),
                ('sirket', models.CharField(max_length=5000, verbose_name='Şirket')),
                ('organization_code', models.CharField(max_length=5000, verbose_name='Organization Code')),
                ('department', models.CharField(max_length=5000, verbose_name='Department')),
                ('quantity', models.CharField(max_length=5000, verbose_name='Quantity')),
                ('ust_ekipman', models.CharField(max_length=5000, verbose_name='Üst Ekipman')),
            ],
        ),
        migrations.CreateModel(
            name='RaporReferanslari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorgu_no', models.CharField(max_length=5000, verbose_name='Sorgu No')),
                ('ref', models.CharField(max_length=5000, verbose_name='Ref')),
                ('ekipman_parca_kodu', models.CharField(max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(max_length=5000, verbose_name='Parça Tanımı')),
                ('grup_tanimi', models.CharField(max_length=5000, verbose_name='Grup Tanımı')),
                ('rapor_tanimi', models.CharField(max_length=5000, verbose_name='Rapor Tanımı')),
                ('ref_grup', models.CharField(max_length=5000, verbose_name='Ref Grup')),
                ('kategori', models.CharField(max_length=5000, verbose_name='Kategori')),
                ('analiz_no', models.CharField(max_length=5000, verbose_name='Analiz No')),
            ],
        ),
    ]
