# Generated by Django 3.2.3 on 2021-05-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0002_hamveri_raporreferanslari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamveri',
            old_name='department',
            new_name='department_code',
        ),
    ]
