# Generated by Django 3.2.3 on 2021-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0003_rename_department_hamveri_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamveri',
            name='ust_ekipman',
            field=models.CharField(default='', max_length=5000, verbose_name='Üst Ekipman'),
        ),
    ]
