# Generated by Django 3.2.3 on 2021-05-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0004_alter_hamveri_ust_ekipman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamveri',
            old_name='saha_kod',
            new_name='saha_kodu',
        ),
    ]
