# Generated by Django 3.2.3 on 2021-05-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0005_rename_saha_kod_hamveri_saha_kodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorguList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorgu_no', models.CharField(max_length=5000, verbose_name='Sorgu No')),
                ('kontrol', models.CharField(max_length=5000, verbose_name='Kontrol')),
                ('ref_grup', models.CharField(max_length=5000, verbose_name='Ref Grup')),
                ('kategori', models.CharField(max_length=5000, verbose_name='Kategori')),
                ('check', models.CharField(max_length=5000, verbose_name='Check')),
            ],
        ),
        migrations.AlterField(
            model_name='hamveri',
            name='kts_saha_no',
            field=models.CharField(default='', max_length=50, verbose_name='KTS Saha No'),
        ),
    ]
