# Generated by Django 3.1.4 on 2021-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0006_auto_20210522_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamveri',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hamveri',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_1',
            field=models.IntegerField(max_length=50, verbose_name='Referans-1'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_2',
            field=models.IntegerField(max_length=50, verbose_name='Referans-2'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_3',
            field=models.IntegerField(max_length=50, verbose_name='Referans-3'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_4',
            field=models.IntegerField(max_length=50, verbose_name='Referans-4'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_5',
            field=models.IntegerField(max_length=50, verbose_name='Referans-5'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_6',
            field=models.IntegerField(max_length=50, verbose_name='Referans-6'),
        ),
        migrations.AlterField(
            model_name='raporreferanslari',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sorgulist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
