# Generated by Django 3.1.4 on 2021-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0007_auto_20210522_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_1',
            field=models.IntegerField(verbose_name='Referans-1'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_2',
            field=models.IntegerField(verbose_name='Referans-2'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_3',
            field=models.IntegerField(verbose_name='Referans-3'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_4',
            field=models.IntegerField(verbose_name='Referans-4'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_5',
            field=models.IntegerField(verbose_name='Referans-5'),
        ),
        migrations.AlterField(
            model_name='raporgirdiler',
            name='ref_6',
            field=models.IntegerField(verbose_name='Referans-6'),
        ),
    ]
