# Generated by Django 3.1.4 on 2021-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0008_auto_20210522_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamveri',
            name='ekipman_seri_no',
            field=models.CharField(default='', max_length=5000, verbose_name='Ekipman Seri No'),
        ),
    ]
