# Generated by Django 3.1.4 on 2021-05-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0011_log_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='saha_kod',
            field=models.CharField(default='', max_length=50, verbose_name='Saha Kod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='saha_no',
            field=models.CharField(default='', max_length=50, verbose_name='Saha No'),
            preserve_default=False,
        ),
    ]
