# Generated by Django 3.1.4 on 2021-05-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0014_rapor'),
    ]

    operations = [
        migrations.AddField(
            model_name='raporgirdiler',
            name='rapor_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rapor', to='excel_app.rapor'),
            preserve_default=False,
        ),
    ]
